### PR TITLE
Fix error 403 for Youtube oembed endpoint (Ref. #95).

### LINKED ISSUE #95: WARNING sc.embedder HTTP Error 403: Forbidden for youtube urls
Calling the oembed endpoint is giving `403`:

`curl 'http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=Pw6yWmTnWlQ'`

```json
{
  "error": {
    "code": 403,
    "message": "SSL is required to perform this operation.",
    "status": "PERMISSION_DENIED"
  }
}
```

Changing the endpoint scheme in https://github.com/collective/sc.embedder/blob/942e6343f360642ba79e8e777b95faa9acb4fd73/src/sc/embedder/utility.py#L60 to use `https` fixes the issue:

`curl 'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=Pw6yWmTnWlQ'`

```json
{"title":"Entenda o que \u00e9 o projeto Libras Gov","author_name":"Planalto","author_url":"https://www.youtube.com/user/PalaciodoPlanalto","type":"video","height":113,"width":200,"version":"1.0","provider_name":"YouTube","provider_url":"https://www.youtube.com/","thumbnail_height":360,"thumbnail_width":480,"thumbnail_url":"https://i.ytimg.com/vi/Pw6yWmTnWlQ/hqdefault.jpg","html":"\u003ciframe width=\u0022200\u0022 height=\u0022113\u0022 src=\u0022https://www.youtube.com/embed/Pw6yWmTnWlQ?feature=oembed\u0022 frameborder=\u00220\u0022 allow=\u0022accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\u0022 allowfullscreen\u003e\u003c/iframe\u003e"}```

### PR DESCRIPTION
**Pull request by idgserpro**

### CODE REVIEW

**Comment by idgserpro** [comment]
@hvelarde the errors here were happening even before this PR as can be seen in https://travis-ci.org/github/collective/sc.embedder/jobs/751884679.

I'm not familiar with these errors. Any hints?

**Comment by idgserpro** [comment]
For the Unauthorized (https://www.youtube.com/watch?v=cwWzpkgwWuU) and Not Found urls (https://www.youtube.com/watch?v=fpDw3s7XJKo) they return a html response (https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=cwWzpkgwWuU and https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=fpDw3s7XJKo) containing only these strings.

So, [`get_data` from the utility always return None](https://github.com/collective/sc.embedder/blob/c5d1eef09fca938a3bf3deb35d1914236f0b186c/src/sc/embedder/utility.py#L44), never entering in the exception in [content's `get_data`](https://github.com/collective/sc.embedder/blob/c5d1eef09fca938a3bf3deb35d1914236f0b186c/src/sc/embedder/content/embedder.py#L213) and never printing a message which is supposed to be printed with `api.portal.show_message`, and checked in the tests. Adding `status_code` with HTTMock will not trigger the exception thus not printing what is supposed to be checked in the broken tests.

I didn't grasp why it was working before, or what's the best way to handle this situation. Should we add in https://github.com/collective/sc.embedder/blob/c5d1eef09fca938a3bf3deb35d1914236f0b186c/src/sc/embedder/utility.py#L44 a check to see if it's Youtube, check the `Unauthorized`and `Not Found` strings, and properly raise a `HTTPError` with the expected status codes which will be used by content's `get_data` to properly print the error message? Or return a dict with a status_code, and check this status code in content's `get_data`?

Any suggestions?

**Comment by hvelarde** [comment]
sorry, guys... I have no head for this today :-)

**Comment by idgserpro** [comment]
Well, right now, the oembed endpoint for youtube is broken for everyone using sc.embedder (just do a git clone master and try to load information about any youtube video). IMHO, since youtube is largely used and it's all broken right now in this package, we can create a new release just with this fix and later we could fix these tests after more thought.

**Comment by hvelarde** [comment]
do you mind to skip those tests, add a TODO note to fix them later and open a new issue to describe the problem?

**Comment by idgserpro** [comment]
Thanks! Would you mind creating a new 1.5.1 release as well?

**Comment by idgserpro** [comment]
@hvelarde Can we have a new release? Right now, YouTube functionality is broken... :cry:

**Comment by hvelarde** [comment]
sorry guys, now you're maintainers of the project and you can make releases.

**Comment by idgserpro** [comment]
Can you make the invitation again? Unfortunately the token has expired.

Thanks!

**Comment by hvelarde** [comment]
done!

**Comment by idgserpro** [comment]
Thanks again!

**Comment by idgserpro** [comment]
@hvelarde Just tried a `fullrelease` (thus https://pypi.org/project/sc.embedder/1.5.1/ is available now) but we can't push to `master`:

```bash
git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 411 bytes | 411.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected.
To https://github.com/collective/sc.embedder.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/collective/sc.embedder.git'
```

Do we have the available permissions?

**Comment by hvelarde** [comment]
please check again...

**Comment by idgserpro** [comment]
Now on master! Thanks!

**Pull request merged**
